name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: mamba setup
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    # Build the book
    - name: Build the book
      run: jupyter-book build .
      shell: bash -el {0}

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        enable_jekyll: false
